/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * DVD Shop API
 * API for DVD Shop
 * OpenAPI spec version: 1.0
 */
export interface ProcessCartItemDtoRequest {
  id: number;
  quantity: number;
}

export interface ProcessCartDtoRequest {
  items: ProcessCartItemDtoRequest[];
}

export interface ProcessCartItemDiscountResponse {
  discountRatePercent: number;
  discountAmount: number;
}

export interface ProcessCartItemResponse {
  id: number;
  title: string;
  unitPrice: number;
  finalPrice: number;
  discount: ProcessCartItemDiscountResponse;
  quantity: number;
}

export interface ProcessCartResponse {
  items: ProcessCartItemResponse[];
  total: number;
  totalDiscount: number;
}

export interface MovieItemResponseDto {
  id: number;
  title: string;
  price: number;
}

export interface MoviesListResponseDto {
  items: MovieItemResponseDto[];
}

