/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * DVD Shop API
 * API for DVD Shop
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ProcessCartDtoRequest,
  ProcessCartResponse
} from '../dVDShopAPI.schemas';

import { apiClient } from '../../lib/api-client';




/**
 * @summary Process cart
 */
export const cartControllerProcess = (
    processCartDtoRequest: ProcessCartDtoRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ProcessCartResponse>(
      {url: `/cart/process`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: processCartDtoRequest, signal
    },
      );
    }
  


export const getCartControllerProcessMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cartControllerProcess>>, TError,{data: ProcessCartDtoRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cartControllerProcess>>, TError,{data: ProcessCartDtoRequest}, TContext> => {

const mutationKey = ['cartControllerProcess'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cartControllerProcess>>, {data: ProcessCartDtoRequest}> = (props) => {
          const {data} = props ?? {};

          return  cartControllerProcess(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CartControllerProcessMutationResult = NonNullable<Awaited<ReturnType<typeof cartControllerProcess>>>
    export type CartControllerProcessMutationBody = ProcessCartDtoRequest
    export type CartControllerProcessMutationError = unknown

    /**
 * @summary Process cart
 */
export const useCartControllerProcess = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cartControllerProcess>>, TError,{data: ProcessCartDtoRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cartControllerProcess>>,
        TError,
        {data: ProcessCartDtoRequest},
        TContext
      > => {
      return useMutation(getCartControllerProcessMutationOptions(options), queryClient);
    }
    