/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * DVD Shop API
 * API for DVD Shop
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MoviesListResponseDto
} from '../dVDShopAPI.schemas';

import { apiClient } from '../../lib/api-client';




export const moviesControllerList = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<MoviesListResponseDto>(
      {url: `/movies/list`, method: 'GET', signal
    },
      );
    }
  



export const getMoviesControllerListQueryKey = () => {
    return [
    `/movies/list`
    ] as const;
    }

    
export const getMoviesControllerListQueryOptions = <TData = Awaited<ReturnType<typeof moviesControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moviesControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMoviesControllerListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof moviesControllerList>>> = ({ signal }) => moviesControllerList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moviesControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MoviesControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof moviesControllerList>>>
export type MoviesControllerListQueryError = unknown


export function useMoviesControllerList<TData = Awaited<ReturnType<typeof moviesControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moviesControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moviesControllerList>>,
          TError,
          Awaited<ReturnType<typeof moviesControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMoviesControllerList<TData = Awaited<ReturnType<typeof moviesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moviesControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moviesControllerList>>,
          TError,
          Awaited<ReturnType<typeof moviesControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMoviesControllerList<TData = Awaited<ReturnType<typeof moviesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moviesControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMoviesControllerList<TData = Awaited<ReturnType<typeof moviesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moviesControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMoviesControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




